modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="arlighttetrisportraitfix"
version="${mod_version}"
displayName="ArlightTetris Skin Image Hotfix"
description='''
Renderiza las skins de los rankings de ArlightTetris como retratos 2D completos dentro de los paneles.
'''

[[dependencies.arlighttetrisportraitfix]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.arlighttetrisportraitfix]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="CLIENT"

[[dependencies.arlighttetrisportraitfix]]
modId="arlighttetris"
type="required"
versionRange="[0.6.17,)"
ordering="AFTER"
side="CLIENT"
